### ISSUE TITLE
Installation error with petsc > 3.7.3

### ISSUE THREAD

**Issue by Lionel68** [Pbleonard/GFlow#20]
I installed the latest version (3.7.6) of petsc on my ubuntu 16.04 and after changing the $PETSC_DIR in the makefile I get the following error:
~/Downloads/GFlow-0.1.6-alpha$ make
mpicc -g -Wall -O2 -std=c11 -D_GNU_SOURCE -isystem /usr/lib/petscdir/3.7.6/petsc-3.7.6/include -c gflow.c -o gflow.o
In file included from /usr/lib/petscdir/3.7.6/petsc-3.7.6/include/petscbag.h:4:0,
                 from /usr/lib/petscdir/3.7.6/petsc-3.7.6/include/petsc.h:5,
                 from gflow.c:27:
/usr/lib/petscdir/3.7.6/petsc-3.7.6/include/petscsys.h:14:23: fatal error: petscconf.h: No such file or directory
compilation terminated.
Makefile:12: recipe for target 'gflow.o' failed
make: *** [gflow.o] Error 1

It seems that the file architecture is not the same between 3.7.3 and 3.7.6, are you planning on updating the makefile do this new version of petsc? Note that in the readme you specify: " but it needs PETSc >= 3.7.3", it does not seems to work for me.

**Comment by eduffy** [comment]
Hi @Lionel68 -Can you double-check your `PETSC_DIR` variable.  On my system its `/usr/local/Cellar/petsc/3.7.3/real`.  Do you have a `/usr/lib/petscdir/3.7.6/petsc-3.7.6/real` directory?

**Comment by Lionel68** [comment]
Hi @eduffy, here is the PETSC_DIR variable I set on line 7 of the GFlow makefile: `PETSC_DIR=/usr/lib/petscdir/3.7.6/petsc-3.7.6`, and here are the folders/files in that folder:
`arch-linux2-c-debug      configure          gmakefile   makefile   src
bin                      configure.log      include     make.log   systems
bitbucket-pipelines.yml  configure.log.bkp  interfaces  RDict.log  TAGS
CMakeLists.txt           CONTRIBUTING       lib         setup.py   tutorials
config                   CTAGS              LICENSE     share`
It seems that the make file is looking for petscconf.h here:` /usr/lib/petscdir/3.7.6/petsc-3.7.6/include`, when it is actually in this folder: `/usr/lib/petscdir/3.7.6/petsc-3.7.6/arch-linux2-c-debug/include`

**Comment by chaw0023** [comment]
I am trying to compile with `petsc v3.4.5` and I am getting the same error. @lionel68 were you able to resolve this?

`In file included from petsc-3.4.5/include/petscis.h:7:0,
                 from petsc-3.4.5/include/petscvec.h:9,
                 from petsc-3.4.5/include/petscmat.h:6,
                 from petsc-3.4.5/include/petscpc.h:6,
                 from petsc-3.4.5/include/petscksp.h:6,
                 from ../../../Src/Extern/PETSc/AMReX_PETSc.cpp:2:
petsc-3.4.5/include/petscsys.h:14:23: fatal error: petscconf.h: No such file or directory
 #include <petscconf.h>
                       ^
compilation terminated.`
